In [1]:
import numpy as np
from helpers import save_adj_matrix, normalize_matrix

In [2]:
INPUT_MATRIX = "output/lrc_proc_2024-04-05_16-02-04.npy"
OUTPUT_MATRIX = "output/lrc_adj_2024-04-05_16-02-04.txt"

In [3]:
p_values = np.load(INPUT_MATRIX)
p_values

array([[       nan, 0.18549538,        nan, ..., 0.86380181, 0.33186799,
        0.54579055],
       [0.18549538,        nan, 0.31977329, ..., 0.00421311,        nan,
        0.50303907],
       [       nan, 0.31977329,        nan, ..., 0.08411319, 0.16788815,
               nan],
       ...,
       [0.86380181, 0.00421311, 0.08411319, ...,        nan, 0.17188849,
        0.362081  ],
       [0.33186799,        nan, 0.16788815, ..., 0.17188849,        nan,
        0.02563463],
       [0.54579055, 0.50303907,        nan, ..., 0.362081  , 0.02563463,
               nan]])

In [4]:
significance_matrix = 1/p_values
significance_matrix

array([[         nan,   5.3909699 ,          nan, ...,   1.15767296,
          3.0132463 ,   1.83220468],
       [  5.3909699 ,          nan,   3.12721556, ..., 237.35447031,
                 nan,   1.98791715],
       [         nan,   3.12721556,          nan, ...,  11.88874224,
          5.9563465 ,          nan],
       ...,
       [  1.15767296, 237.35447031,  11.88874224, ...,          nan,
          5.81772529,   2.76181298],
       [  3.0132463 ,          nan,   5.9563465 , ...,   5.81772529,
                 nan,  39.00973596],
       [  1.83220468,   1.98791715,          nan, ...,   2.76181298,
         39.00973596,          nan]])

In [5]:
significance_matrix = np.nan_to_num(significance_matrix, nan=0)
significance_matrix

array([[  0.        ,   5.3909699 ,   0.        , ...,   1.15767296,
          3.0132463 ,   1.83220468],
       [  5.3909699 ,   0.        ,   3.12721556, ..., 237.35447031,
          0.        ,   1.98791715],
       [  0.        ,   3.12721556,   0.        , ...,  11.88874224,
          5.9563465 ,   0.        ],
       ...,
       [  1.15767296, 237.35447031,  11.88874224, ...,   0.        ,
          5.81772529,   2.76181298],
       [  3.0132463 ,   0.        ,   5.9563465 , ...,   5.81772529,
          0.        ,  39.00973596],
       [  1.83220468,   1.98791715,   0.        , ...,   2.76181298,
         39.00973596,   0.        ]])

In [6]:
significance_matrix = normalize_matrix(significance_matrix)
significance_matrix

array([[0.00000000e+00, 1.06170573e-05, 0.00000000e+00, ...,
        2.27993856e-06, 5.93433262e-06, 3.60837147e-06],
       [1.06170573e-05, 0.00000000e+00, 6.15878539e-06, ...,
        4.67449466e-04, 0.00000000e+00, 3.91503396e-06],
       [0.00000000e+00, 6.15878539e-06, 0.00000000e+00, ...,
        2.34138679e-05, 1.17305185e-05, 0.00000000e+00],
       ...,
       [2.27993856e-06, 4.67449466e-04, 2.34138679e-05, ...,
        0.00000000e+00, 1.14575158e-05, 5.43915605e-06],
       [5.93433262e-06, 0.00000000e+00, 1.17305185e-05, ...,
        1.14575158e-05, 0.00000000e+00, 7.68263612e-05],
       [3.60837147e-06, 3.91503396e-06, 0.00000000e+00, ...,
        5.43915605e-06, 7.68263612e-05, 0.00000000e+00]])

In [7]:
np.savetxt(OUTPUT_MATRIX, significance_matrix, delimiter=' ')